site_name: Stakater KubeStack+
docs_dir: content
site_url: https://docs.stakater.com/kubestackplus/
repo_url: https://github.com/stakater/kubestackplus-docs
edit_uri: blob/main/content/
use_directory_urls: false
strict: true
theme:
  logo: assets/images/logo.svg
  logo_light: assets/images/favicon.svg
  logo_dark: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
nav:
  - Get Started:
      - index.md
      - about/service-definition.md
      - about/responsibilities.md
  - Platform Setup:
      - platform-setup/index.md
      - Concepts:
          - platform-setup/explanation/gitops-intro.md
          - platform-setup/explanation/gitops-structure.md
          - platform-setup/explanation/types-of-environments.md
      - Bootstrap:
          - platform-setup/tutorials/configure-infra-gitops-repo.md
          - platform-setup/tutorials/configure-apps-gitops-repo.md
      - Identity & Access:
          - platform-setup/how-to-guides/keycloak-idp.md
          - platform-setup/how-to-guides/google-idp.md
          - platform-setup/how-to-guides/azure-idp.md
          - platform-setup/how-to-guides/azure-gso.md
          - platform-setup/how-to-guides/saml-idp.md
          - platform-setup/how-to-guides/authorization-roles.md
          - platform-setup/how-to-guides/user-access.md
      - Networking:
          - platform-setup/how-to-guides/custom-domains.md
          - platform-setup/how-to-guides/tls-certs.md
          - platform-setup/how-to-guides/http01-certs.md
      - Day-2 Operations:
          - platform-setup/how-to-guides/add-a-new-environment-to-application.md
  - Deploy:
      - develop/explanation/inner-outer-loop.md
      - develop/explanation/plan-your-deployment.md
      - develop/tutorials/deploy-demo-app.md
      - develop/how-to-guides/build-and-push-your-image/build-and-push-your-image.md
      - develop/how-to-guides/package-and-push-your-chart/package-and-push-your-chart.md
      - develop/how-to-guides/deploy-app-with-argocd-and-helm/deploy-app-with-argocd-and-helm.md
      - develop/how-to-guides/expose-applications-to-internet/expose-applications-to-internet.md
      - develop/how-to-guides/rewriting-path-annotation/path-rewriting.md
      - operate/secure-routes.md
      - develop/how-to-guides/promote-your-application/promote-your-application.md
      - develop/tutorials/outer-loop/access-cluster/access-the-cluster.md
      - develop/tutorials/outer-loop/promote-application/promote-app.md
  - Develop:
      - develop/explanation/local-development-workflow.md
      - develop/explanation/developer-training.md
      - develop/explanation/production-best-practices.md
      - Inner Loop:
          - develop/tutorials/inner-loop/prepare-environment/prepare-env.md
          - develop/tutorials/inner-loop/about-application/about-application.md
          - develop/tutorials/inner-loop/access-the-cluster/access-the-cluster.md
          - develop/tutorials/inner-loop/containerize-app/containerize-app.md
          - develop/tutorials/inner-loop/package-app/package-app.md
          - develop/tutorials/inner-loop/deploy-app/deploy-app.md
          - develop/tutorials/inner-loop/add-secret/add-secrets.md
          - develop/tutorials/inner-loop/add-configmap/add-configmaps.md
          - develop/tutorials/inner-loop/configure-probes/configure-probes.md
          - develop/tutorials/inner-loop/add-storage/persist-app.md
          - develop/tutorials/inner-loop/expose-app/expose-app.md
          - develop/tutorials/inner-loop/validate-logs/validate-logs.md
          - develop/tutorials/inner-loop/monitor-your-app/monitor-your-app.md
          - develop/tutorials/inner-loop/expose-metrics/expose-metrics.md
          - develop/tutorials/inner-loop/add-alerts/add-alerts.md
          - develop/tutorials/inner-loop/synthetic-monitoring/synthetic-monitoring.md
          - develop/tutorials/inner-loop/add-grafana-dashboard/add-grafana-dashboard.md
          - develop/tutorials/inner-loop/scale-app/scale-app.md
          - develop/tutorials/inner-loop/validate-auto-reload/validate-auto-reload.md
          - develop/tutorials/inner-loop/add-backup-schedule/backup-restore.md
          - develop/tutorials/inner-loop/add-pdb/add-pdb.md
          - develop/tutorials/inner-loop/add-network-policy/add-network-policy.md
          - develop/tutorials/inner-loop/tilt-zero-to-hero/step-by-step-guide.md
      - Debugging:
          - develop/how-to-guides/deploy-multiple-apps-with-tilt/deploy-multiple-apps-with-tilt.md
          - develop/how-to-guides/remote-debugging/remote-debugging-dotnet.md
          - develop/how-to-guides/remote-debugging-mirrord/remote-debugging-mirrord-tilt.md
  - Observe:
      - managed-addons/monitoring-stack/overview.md
      - managed-addons/monitoring-stack/stack.md
      - Metrics & Alerts:
          - managed-addons/monitoring-stack/app-uptime.md
          - managed-addons/monitoring-stack/app-alerts.md
          - managed-addons/monitoring-stack/workload-application-alerts.md
          - managed-addons/monitoring-stack/predefined-prometheusrules.md
          - develop/how-to-guides/expose-spring-boot-metrics/expose-spring-boot-metrics.md
      - Dashboards:
          - managed-addons/monitoring-stack/grafana-dashboard.md
      - Logs:
          - managed-addons/logging-stack/overview.md
          - managed-addons/monitoring-stack/log-alerts.md
      - Traces:
          - managed-addons/tracing/overview.md
          - managed-addons/opentelemetry/overview.md
      - Uptime:
          - managed-addons/imc/overview.md
          - managed-addons/imc/tutorial/add-configuration.md
          - managed-addons/imc/tutorial/add-monitors.md
          - managed-addons/monitoring-stack/downtime-notifications-uptimerobot.md
  - Secure:
      - secure/overview.md
      - secure/deploying-secrets.md
      - secure/backup.md
      - Backup & Restore:
          - operate/velero-stateful-app-example.md
          - operate/velero-restore-with-gitops.md
          - operate/volume-expansion.md
      - Compliance Frameworks:
          - secure/gdpr-eu.md
          - secure/iso27k1.md
          - secure/nist-sp-800-171.md
          - secure/bsi-it-grundschutz.md
          - secure/cis.md
          - secure/soc2-type2.md
          - secure/toms.md
          - secure/subprocessors.md
          - secure/hipaa.md
          - secure/dora.md
  - Managed Addons:
      - managed-addons/overview.md
      - Dev Ready:
          - ArgoCD:
              - managed-addons/argocd/overview.md
              - managed-addons/argocd/for-administrators/availability.md
              - managed-addons/argocd/for-administrators/installation.md
              - managed-addons/argocd/for-administrators/observability.md
              - managed-addons/argocd/for-administrators/resource-requirements.md
          - Tronador:
              - managed-addons/tronador/overview.md
          - Renovate:
              - managed-addons/renovate/overview.md
              - managed-addons/renovate/how-to-guides/automerge.md
              - managed-addons/renovate/how-to-guides/run-locally.md
          - Forecastle:
              - managed-addons/forecastle/overview.md
              - managed-addons/forecastle/tutorial/add-forecastle-app.md
          - Tilt:
              - managed-addons/tilt/overview.md
              - managed-addons/mirrord/tutorial/mirrod-setup.md
          - Reloader:
              - managed-addons/reloader/overview.md
              - managed-addons/reloader/tutorial/configure-resources.md
          - Stakater Application Helm Chart:
              - managed-addons/helm-leader-chart/overview.md
      - Ops Ready:
          - Multi Tenant Operator:
              - managed-addons/mto/overview.md
          - Velero:
              - managed-addons/velero/overview.md
              - managed-addons/velero/introduction.md
              - managed-addons/velero/backup-restore.md
              - managed-addons/velero/cli.md
              - managed-addons/velero/limitations.md
              - managed-addons/velero/cleanup.md
              - managed-addons/velero/troubleshooting.md
          - Descheduler:
              - managed-addons/descheduler/overview.md
          - Autoscaling:
              - managed-addons/vertical-pod-autoscaler/overview.md
              - managed-addons/horizontal-pod-autoscaler/overview.md
              - managed-addons/custom-metrics-autoscaler/overview.md
          - Networking:
              - managed-addons/cert-manager/overview.md
              - managed-addons/external-dns/overview.md
              - managed-addons/service-mesh/overview.md
          - Databases (coming soon):
              - managed-addons/postgres/tutorial/connect-to-postgres-cli/connect-to-postgres-cli.md
              - managed-addons/redis/tutorial/connect-to-redis-cli/connect-to-redis-cli.md
      - Compliance Ready:
          - OpenBao:
              - managed-addons/vault/overview.md
          - External Secrets Operator:
              - managed-addons/external-secrets-operator/overview.md
          - Cert Manager:
              - managed-addons/cert-manager/overview.md
      - Optional Add-ons:
          - RHACS:
              - managed-addons/rhacs/overview.md
              - managed-addons/rhacs/accessing-rhacs.md
              - managed-addons/rhacs/permissions.md
  - Help:
      - help/support/support.md
      - help/faq-platform.md
      - help/faq-administrators.md
      - Kubernetes Concepts:
          - help/k8s-concepts/storage-basics.md
          - help/k8s-concepts/cloud-native-app.md
          - help/k8s-concepts/helm.md
          - help/k8s-concepts/high-availability.md

extra:
  product_name: KubeStack+
  product_name_lower: kubestackplus

plugins:
  - macros
  - include-markdown
  - mkdocs-video
